#!/usr/bin/env bash
#This script displays "Best School" from 0 to 10 but displays "Hi" on 9th trial

a=1
while [ $a -le 10 ]
do
if [ $a -eq 9 ]
then
	echo "Hi"
else
	echo "Best School"
fi
((a++))
done
