#!/usr/bin/env bash
# A script that prints a string a number of times

i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	i=$(( i + 1 ))
done
