#!/usr/bin/env bash
#Script to display "bad luck from China" after 4th iteration
#display "bad luck from Japan" after 9th iteration
#display "bad luck from Italy" after 17th iteration

a=1
while [ $a -le 20 ]
do
	if [ $a -eq 4 ]
	then
		echo "$a"
		echo "bad luck from China"
	elif [ $a -eq 9 ]
	then
		echo "$a"
		echo "bad luck from Japan"
	elif [ $a -eq 17 ]
	then
		echo "$a"
		echo "bad luck from Italy"
	else
		echo "$a"
	fi
	((a++))
done
