#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes

min=1
hr=0

echo "Hour: $hr"
while [ $min -ne 60 ]
do
	if [ $min -eq 59 ] && [ $hr -ne 12 ]
	then
		hr=$(( hr + 1 ))
		echo "$min"
		echo "Hour: $hr"
		min=0
	fi

	echo "$min"

	min=$(( min + 1 ))
done
